events {
    worker_connections 1024;
}

http {
    server_tokens off;

    resolver 127.0.0.11 valid=10s;

    gzip on;
    gzip_types text/plain text/css application/json application/javascript text/xml application/xml image/svg+xml;
    gzip_min_length 1024;

    client_max_body_size 20M;

    proxy_connect_timeout 60s;
    proxy_send_timeout    60s;
    proxy_read_timeout    120s;

    # Header Keamanan Global
    add_header X-Frame-Options           "SAMEORIGIN"                      always;
    add_header X-Content-Type-Options    "nosniff"                         always;
    add_header X-XSS-Protection          "1; mode=block"                   always;
    add_header Referrer-Policy           "strict-origin-when-cross-origin" always;
    add_header Content-Security-Policy   "default-src 'self' http: https: data: blob: 'unsafe-inline' 'unsafe-eval';" always;

    # 1. Frontend Vue.js
    server {
        listen 80;
        server_name lomba.test;

        proxy_set_header Host              $host;
        proxy_set_header X-Real-IP         $remote_addr;
        proxy_set_header X-Forwarded-For   $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;

        location / {
            set $frontend_upstream frontend:80;
            proxy_pass http://$frontend_upstream;
        }
    }

    # 2. Backend Laravel API
    server {
        listen 80;
        server_name api.lomba.test;

        proxy_set_header Host              $host;
        proxy_set_header X-Real-IP         $remote_addr;
        proxy_set_header X-Forwarded-For   $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;

        location / {
            set $backend_upstream backend_nginx:80;
            proxy_pass http://$backend_upstream;
        }
    }

    # 3. phpMyAdmin
    server {
        listen 80;
        server_name pma.lomba.test;

        proxy_set_header Host              $host;
        proxy_set_header X-Real-IP         $remote_addr;
        proxy_set_header X-Forwarded-For   $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;

        location / {
            set $phpmyadmin_upstream phpmyadmin:80;
            proxy_pass http://$phpmyadmin_upstream;
        }
    }
}